---
name: events-unique-name-12345
services:
  eventsapi:
    image: ${DOCKER_REGISTRY-}eventsapi
    build:
      context: .
      dockerfile: EventsAPI/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development  
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
  eventsfront:
    image: ${DOCKER_REGISTRY-}eventsfront
    build:
      context: .
      dockerfile: eventsreact/Dockerfile
    ports:
      - 3000:4173
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_password
      POSTGRES_DB: eventsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
